### ISSUE TITLE
Erlang 18 - make fails

### ISSUE THREAD

**Issue by jesteracer** [tim/erlang-oauth#25]
Getting this on erlang 18
{"init terminating in do_boot",{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
make: *** [compile] User defined signal 2

**Comment by jkxyz** [comment]
:+1: 

Running both `erl -make` and `make` gives the error:

```
{"init terminating in do_boot",{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```

**Comment by tim** [comment]
@jesteracer @jkxyz Works for me using OTP 18.0 built from source. The make module is part of the tools application, which should come as standard.

How did you install erlang?

**Comment by nemski** [comment]
I'm having the same issue, installed OTP on Debian Jessie with apt:

```sh
nemski@zeus:~/src/Primelix/deps/erlang-oauth$ aptitude show erlang-base
Package: erlang-base
State: installed
Automatically installed: yes
Version: 1:18.0
Priority: optional
Section: interpreters
Maintainer: Debian Erlang Packagers <pkg-erlang-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 14.1 M
Depends: procps, libc6 (>= 2.14), libtinfo5, zlib1g (>= 1:1.2.2)
```

**Comment by larrylv** [comment]
I'm having the same issue, installed on Ubuntu with:

```
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
```

`erl`'s output:

```
$ erl
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
1>
```

**Comment by larrylv** [comment]
By the way, it works for me using OTP 18.0 on my Mac, but doesn't work on Ubuntu.

**Comment by larrylv** [comment]
Oh, I think I know what's missing. Solved this issue by `sudo apt-get install erlang`. It seems like elixir doesn't need full dependencies but `erlang-oauth` does.

@jesteracer @jkxyz @nemski Could you try something like install the full erlang to see if it could solve this issue?

**Comment by tim** [comment]
@larrylv That would make sense. It works fine with OTP 18.0 on my mac, and on travis. If you're using elixir, would something like [oauther](https://hex.pm/packages/oauther) be easier to work with?

**Comment by larrylv** [comment]
@tim Thanks for you suggestion. I use [extwitter](https://github.com/parroty/extwitter) for interacting with twitter api, and it uses `erlang-oauth`, so I don't have any choice. 😅

**Comment by tim** [comment]
@larrylv Understandable if you can't control the dependencies. By the looks of it extwitter depends on OTP directly (for inets, ssl, and crypto), so doesn't make sense to not have it installed.

If anyone else runs into a similar error please make sure you have Erlang OTP installed.
