### ISSUE TITLE
Windows NMAKE

### ISSUE THREAD

**Issue by LauriePaulin** [tim/erlang-oauth#31]
Hi,

Will this package work on Windows please?  I am getting this error on "mix ecto.setup":

`'make' is not recognized as an internal or external command`

Which is understandable as MAKE is Linux and the Windows equivalent is NMAKE.

Thanks for any assistance.

**Comment by tim** [comment]
Try installing MinGW. Reading that might help:

* Appendix B of [Programming Erlang](https://www.amazon.com/Programming-Erlang-Concurrent-Pragmatic-Programmers/dp/193778553X/)
* http://stackoverflow.com/questions/12881854/how-to-use-gnu-make-on-windows
