### ISSUE TITLE
Compilation fails on Windows 10 ("system cannot find the file specified")

### ISSUE THREAD

**Issue by IRLeif** [tim/erlang-oauth#35]
When compiling this library on Windows 10, this error occurs:

```
C:\erlang-oauth>make
process_begin: CreateProcess(NULL, rm -rf ebin/*.beam, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2
```

`make` is running from: `C:\Program Files (x86)\GnuWin32\bin`

**Comment by KavalarisNikolaos** [comment]
exactly the same problem ...did you come up with any solution after all ? @IRLeif

**Comment by tim** [comment]
The Makefile wasn't meant for windows.

I've removed it in v2, you should be able to build on windows using `erl.exe -make`
