### ISSUE TITLE
2.0 fails to compile with Elixir (mix)

### ISSUE THREAD

**Issue by arjan** [tim/erlang-oauth#37]
Due to the missing makefile it fails to compile:

```
Could not compile :oauth, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
```

**Comment by tim** [comment]
You can compile the code in this repo using `erl -make`, `erl.exe -make` on windows, or `make:all().` from within Erlang. Anything beyond that is up to you. I don't use Elixir but I imagine you could use that compile option.
